apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole-ha.fullname" . }}
  labels:
    {{- include "pihole-ha.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.piholeEnv }}
  {{ $key }}: {{ b64enc $val }}
  {{- end }}
