apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-ha.fullname" . }}-web
  labels:
    {{- include "pihole-ha.labels" . | nindent 4 }}
    instance: primary
  {{- if .Values.service.annotations }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pihole-ha.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "pihole-ha.fullname" . }}-0 
