apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-ha.fullname" . }}-tcp
  labels:
    {{- include "pihole-ha.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "pihole-ha.selectorLabels" . | nindent 4 }}
